stages:
 - build
 - integration-test
 - unit-test
#  - plugin-test

build:
  stage: build
  before_script:
   - pwd
   - rm -rf ./build
   - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
   - git submodule update --init --recursive
   - pip3 install distro
  script:
   - cd cd-scripts
   - cp config-ci.py config.py
   - ./deploy.py --build-beos
   - ./deploy.py --initialize-beos
  after_script: 
   - cd cd-scripts
   - cat beos_deploy_main.log
  cache: {}
  tags:
   - ryzen
  allow_failure: false
  artifacts:
    paths:
     - build/
  
integration-test:
  stage: integration-test
  script: 
  - cd build/beos-autobuild
  - make test
  when: manual
  cache: {}
  tags:
  - ryzen
  allow_failure: true
  dependencies:
  - build
  artifacts:
   paths:
    - build/

unit-test:
  stage: unit-test
  script: 
  - cd build/beos-autobuild/unittests
  - ./unit_test
  when: manual
  cache: {}
  tags:
  - ryzen
  allow_failure: true
  dependencies:
  - integration-test
  # artifacts:
  #  paths
  #   - build/

# currently disabled and not fully configured
# plugin-test:
#   stage: plugin-test
#   script: 
#   - pwd
#   - ./deploy.py --make-beos-plugin-test
#   when: manual
#   cache: {}
#   tags:
#   - ryzen
#   allow_failure: true
#   dependencies:
#   - unit-test
