before_script:
 - pwd

stages:
 - build
 - run

build:
 stage: build
 script:
  - cd cd-scripts
  - cp config-ci.py config.py
  - ./deploy.py --download-source
  - ./deploy.py --build-beos
  only:
  - configure-ci
  
 
run:
  stage: run
  script:
  - cd cd-scripts
  - ./deploy.py --initialize-beos
  only:
  - configure-ci
  when: manual
