stages:
 - build
 - test

build:
  stage: build
  script:
   - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
   - git submodule update --init --recursive
   - pwd
   - pip3 install distro
   - cd cd-scripts
   - cp config-ci.py config.py
   - ./deploy.py --build-beos
   - ./deploy.py --initialize-beos
  cache: {}
  tags:
   - ryzen
  allow_failure: false
  
test:
  stage: test
  script: 
  - cd cd-scripts
  - cp config-ci.py config.py
  - ./deploy.py --make-integration-test
  - ./deploy.py --make-unit-test
  - ./deploy.py --make-beos-plugin-test
  when: manual
  cache: {}
  tags:
  - ryzen
  allow_failure: true
  dependencies:
  - build
