stages:
 - build
 - run

build:
  stage: build
  script:
   - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
   - pwd
   - pip3 install distro
   - cd cd-scripts
   - cp config-ci.py config.py
   - ./deploy.py --download-source
   - ./deploy.py --build-beos
  only:
   - configure-ci
  tags:
   - ryzen
  
 
run:
  stage: run
  script:
  - cd cd-scripts
  - cp config-ci.py config.py
  - ./deploy.py --initialize-beos
  only:
  - configure-ci
  when: manual
  tags:
  - ryzen
