stages:
 - build
 - run

build:
  stage: build
  script:
   - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
   - git submodule update --init --recursive
   - pwd
   - pip3 install distro
   - cd cd-scripts
   - cp config-ci.py config.py
   - ./deploy.py --build-beos
   - ./deploy.py --initialize-beos
  #only:
  # - beos-initial-release
  cache: {}
  tags:
   - ryzen
  allow_failure: false
  
 
#run:
#  stage: run
#  script:
#  - cd cd-scripts
#  - cp config-ci.py config.py
#  - ./deploy.py --initialize-beos
#  #only:
#  #- beos-initial-release
#  when: manual
#  tags:
#  - ryzen
#  allow_failure: false
