stages:
 - build
#  - plugin-test

before_script:
 - pwd

build:
  stage: build
  script:
   - rm -rf ./build
   - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
   - git submodule update --init --recursive
   - pip3 install distro
   - cd cd-scripts
   - cp config-ci.py config.py
   - ./deploy.py --build-beos
   - cat beos_deploy_main.log
   - echo "Stopping old keosd instance"
   - sudo kill -2 $(sudo lsof -t -i:8900)
   - sudo python3 ./wait.py $(sudo lsof -t -i:8900)
   - echo "Stopping old nodeos instance"
   - sudo kill -2 $(sudo lsof -t -i:8888)
   - sudo python3 ./wait.py $(sudo lsof -t -i:8888)
   - ./deploy.py --initialize-beos
   - cat beos_deploy_main.log
   - cd ../build/beos-autobuild/
   - echo "Starting keosd and nodeos"
  #  - sudo python3 ./run.py
   - ./programs/keosd/keosd --http-server-address 192.168.6.144:8900 --wallet-dir /home/syncad/eosio-wallet 2>&1 | tee keosd.log
   - ./programs/cleos/cleos wallet unlock -n beos_master_wallet --password $(cat ./wallet/wallet.dat)
   - ./programs/nodeos/nodeos --max-irreversible-block-age -1 --contracts-console --blocks-dir /home/syncad/tmp/0-eosio/blocks --config-dir /home/syncad/tmp/0-eosio --data-dir /home/syncad/tmp/0-eosio --chain-state-db-size-mb 1024 --enable-stale-production --producer-name eosio --signature-provider EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV=KEOSD:http://192.168.6.144:8900/v1/wallet/sign_digest --http-server-address 192.168.6.144:8888 --plugin eosio::http_plugin --plugin eosio::chain_api_plugin --plugin eosio::producer_plugin --plugin eosio::beos_plugin --plugin eosio::beos_api_plugin --plugin eosio::history_plugin --plugin eosio::history_api_plugin 2>&1 | tee nodeos.log
   - echo "Started keosd instance:"
   - sudo lsof -t -i:8900 || true
   - echo "Started nodeos instance:"
   - sudo lsof -t -i:8888 || true
   - screen -list || true
   - echo "Starting integration tests"
   - make test
   - echo "Cancel previous instance of keosd and nodeos"
   - sudo python3 ./run.py --cancel
   - echo "Removing old .pid files"
   - sudo rm -rf ./run_keosd.pid
   - sudo rm -rf ./run_nodeos.pid
   - echo "Starting keosd and nodeos"
   - sudo python3 ./run.py
   - echo "Started keosd instance:"
   - sudo lsof -t -i:8900 || true
   - echo "Started nodeos instance:"
   - sudo lsof -t -i:8888 || true
   - screen -list || true
   - cd ./unittests
   - echo "Starting unit tests"
   - ./unit_test --log_level=test_suite
   
  cache:
    {}
  tags:
   - ryzen
  allow_failure: false
  environment:
    name: development
    url: http://192.168.6.144:8888/v1/chain/get_info

# currently disabled and not fully configured
# plugin-test:
#   stage: plugin-test
#   script: 
#   - pwd
#   - ./deploy.py --make-beos-plugin-test
#   when: manual
#   cache: {}
#   tags:
#   - ryzen
#   allow_failure: true
