stages:
 - build
 - integration-test
 - unit-test
#  - plugin-test

before_script:
 - pwd
 - rm -rf ./build
 - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
 - eval $(ssh-agent -s)
 - ssh-add <(echo "$SSH_PRIVATE_KEY")
 - git submodule update --init --recursive
 - pip3 install distro

build:
  stage: build
  script:
   - cd cd-scripts
   - cp ./config-ci.py ./config.py
   - ./deploy.py --build-beos
   - cat beos_deploy_main.log
   - ./deploy.py --initialize-beos
   - cat beos_deploy_main.log
  # - kill $(sudo lsof -t -i:8900) || true
  # - ../build/beos-autobuild/programs/keosd/keosd --http-server-address 192.168.6.144:8900 --wallet-dir /home/gitlab-runner/eosio-wallet
  cache: {}
  tags:
   - ryzen
  allow_failure: false
  
deploy:
  stage: build
  script:
   - pwd
   - ls -l
  allow_failure: true
  dependencies:
   - build
  environment:
    name: development
    url: http://192.168.6.144:8888/v1/chain/get_info

integration-test:
  stage: integration-test
  script: 
  - cd cd-scripts
  - cp ./config-ci.py ./config.py
  - ./deploy.py --build-beos
  - cat beos_deploy_main.log
  - ./deploy.py --initialize-beos
  - cat beos_deploy_main.log
  - cd ../build/beos-autobuild
  - make test
  when: manual
  cache: {}
  tags:
  - ryzen
  allow_failure: true
  dependencies:
  - build

unit-test:
  stage: unit-test
  script: 
  - cd cd-scripts
  - cp ./config-ci.py ./config.py
  - ./deploy.py --build-beos
  - ./deploy.py --initialize-beos
  - cat beos_deploy_main.log
  - cd ../build/beos-autobuild/unittests
  - ./unit_test
  when: manual
  cache: {}
  tags:
  - ryzen
  allow_failure: true
  dependencies:
  - build

# currently disabled and not fully configured
# plugin-test:
#   stage: plugin-test
#   script: 
#   - pwd
#   - ./deploy.py --make-beos-plugin-test
#   when: manual
#   cache: {}
#   tags:
#   - ryzen
#   allow_failure: true
