stages:
 - build
 - integration-test
 - unit-test
#  - plugin-test

before_script:
 - pwd

build:
  stage: build
  script:
   - rm -rf ./build
   - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
   - git submodule update --init --recursive
   - pip3 install distro
   - cd cd-scripts
   - cp config-ci.py config.py
   - ./deploy.py --build-beos
   - cat beos_deploy_main.log
   - echo "Stopping old keosd instance"
   - sudo kill $(sudo lsof -t -i:8900) || true
   - echo "Stopping old nodeos instance"
   - sudo kill $(sudo lsof -t -i:8888) || true
   - ./deploy.py --initialize-beos
   - cat beos_deploy_main.log
  cache:
    {}
  artifacts:
    paths:
    - build/*
    - cd-scripts/beos_deploy_main.log
    - cd-scripts/config.py
  tags:
   - ryzen
  allow_failure: false
  environment:
    name: development
    url: http://192.168.6.144:8888/v1/chain/get_info

integration-test:
  stage: integration-test
  script: 
    - cd ./build/beos-autobuild
    - echo "Stopping old keosd instance"
    - sudo kill $(sudo lsof -t -i:8900) || true
    - echo "Stopping old nodeos instance"
    - sudo kill $(sudo lsof -t -i:8888) || true
    - echo "Starting keosd and nodeos"
    - python3 ./run.py
    - make test
  when: manual
  tags:
  - ryzen
  allow_failure: true
  dependencies:
  - build
  artifacts:
    paths:
    - build/*
    - cd-scripts/beos_deploy_main.log
    - cd-scripts/config.py

unit-test:
  stage: unit-test
  script: 
  - cd ./build/beos-autobuild/unittests
  - ./unit_test
  when: manual

  tags:
  - ryzen
  allow_failure: true
  dependencies:
  - build
  artifacts:
    paths:
    - build/*
    - cd-scripts/beos_deploy_main.log
    - cd-scripts/config.py

# currently disabled and not fully configured
# plugin-test:
#   stage: plugin-test
#   script: 
#   - pwd
#   - ./deploy.py --make-beos-plugin-test
#   when: manual
#   cache: {}
#   tags:
#   - ryzen
#   allow_failure: true
